// Generated by CoffeeScript 1.7.1
(function() {
  var CORS_SERVER;

  CORS_SERVER = '127.0.0.1:9292';

  describe('CORS', function() {
    it('should allow access to  resource', function(done) {
      return $.get("http://" + CORS_SERVER + "/status", function(data, status, xhr) {
        expect(data).to.eql('100');
        return done();
      });
    });
    it('should allow PUT access to status resource', function(done) {
      return $.ajax("http://" + CORS_SERVER + "/status", {
        type: 'PUT'
      }).done(function(data, textStatus, jqXHR) {
        expect(data).to.eql('100');
        return done();
      });
    });
    it('should allow DELETE access to status resource', function(done) {
      return $.ajax("http://" + CORS_SERVER + "/status", {
        type: 'DELETE'
      }).done(function(data, textStatus, jqXHR) {
        expect(data).to.eql('100');
        return done();
      });
    });
    it('should allow access to product resource', function(done) {
      return $.get("http://" + CORS_SERVER + "/products", function(data, status, xhr) {
        expect(data).to.eql("Hello, developer! Your products are: MacBook");
        return done();
      });
    });
  });

}).call(this);
